[package]
name = "md5"
version = "1.0.1"
edition = "2021"

[features]
dangerously-enable-md5 = []

[dev-dependencies]
hex-literal = "0.4.1"
md5-reference = { version = "0.10.6", package = "md-5" }
proptest = "1.5.0"
